version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    restart: unless-stopped

  odoo:
    image: odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    networks:
      - odoo-network
    volumes:
      - odoo-data:/var/lib/odoo
    restart: unless-stopped

networks:
  odoo-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
